language: ruby
bundler_args: --without yard guard
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: 1.8.7
    - rvm: ree
    - rvm: rbx-18mode
    - rvm: rbx-18mode
notifications:
  email:
    - mbj@seonic.net
