language: ruby
script: "bundle exec rake ci"
env:
  - TRAVIS=true
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - rbx-2
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --2.0"  # for simplecov
